---
title: "Project 1"
subtitle: "Best Selling Books by 5 Leading Authors"
output: html_notebook
data: 04-18-2025
author: Aby Joe Jose & Meenakshy Manju
---
```{r}
#Importing required libraries
library(dplyr)
library(plotly)
library(ggplot2)
library(viridis)
library(RColorBrewer)
library(scales)
```


```{r}
#Reading the data
data1 <- read.csv('bestsellers with categories.csv')
head(data1)
```
```{r}
#Checking for Null Variables
print(sum(is.na(data1)))
print(nrow(data1))
```

```{r}
#Removing the columns that have Same name, rating, reviews and Genre but with different year. But keeping the first occurrance of the year and price
data_unique <- data1  %>%
  distinct(Name, User.Rating, Reviews, Genre,.keep_all = TRUE)
nrow(data_unique)
```

```{r}
#Creating a new variable score by combining Reviews and User.Rating.

data_unique$Score <- (data_unique$User.Rating * 1000) + data_unique$Reviews
str(data_unique)
```
```{r}
#Getting the top 5 authors based on the mean value of score. 
Top_5_author <- data_unique  %>%
  group_by(Author)  %>%
  summarise(Total_Score = sum(Score))  %>%
  arrange(desc(Total_Score))  %>%
  head(5)
Top_5_author
```
```{r}
# Filtering data based on the top 5 authors

data <- data_unique[data_unique$Author %in% Top_5_author$Author,]
str(data)
```

```{r}
#Top 5 books of the top 5 authors
Top_5_books_of_each_author <- data  %>%
  group_by(Author)  %>% 
  arrange(desc(Score)) %>%
  slice_head(n = 5)  %>% 
  ungroup()
Top_5_books_of_each_author
```
```{r}
# Shortening the name of the books to fit into the graph
Top_5_books_of_each_author$ShortName <- substr(Top_5_books_of_each_author$Name,1,25)
Top_5_books_of_each_author
```

```{r}
# Plotting the Graph
p <- ggplot(Top_5_books_of_each_author, mapping = aes(x = reorder(ShortName,Score), y = Score, fill =Author, text = paste("Name of the book:", Name, '<br>Author:', Author,'<br>Price:', '$',Price,'<br>Genre:' ,Genre,"<br>Score:", Score ))) + 
  geom_col() +
  scale_fill_brewer(type = "qual",palette = 'Set1') + 
  facet_grid(Author~.,scales = "free_y")+
  theme_minimal() + 
  labs(title = "Best Selling Books by 5 Leading Authors",x = NULL, y = 'Score') +
  coord_flip() + 
  scale_y_continuous(labels = function(x) {paste0((x / 1000), "k")}) + 
  theme(strip.text.y = element_blank(),
    strip.background = element_blank())

ggplotly(p, tooltip = 'text')

```


